### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by usuke-inudog** [usuke-inudog/chat-space#12]
# IPアドレス
54.150.252.72

**Comment by miyu-yamamoto** [comment]
香川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ グループに参加した後、1度リロードをしないと自動更新されない**
グループに参加してから1度リロードしないと自動更新が行われません。
ですのでリロードしないでも自動更新されるよう修正をお願いできますでしょうか。
実際に動作をご確認いただく場合は
新しく作成したチャットグループで試してみていただけるといいかと思います。

自動更新に関するカリキュラム
https://master.tech-camp.in/curriculums/1211

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by usuke-inudog** [comment]
修正しました

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※今後実装に関する質問がありましたら、メンターに確認をお願いします！**
